### PR TITLE
Created a basic StackExchange integration

### PR DESCRIPTION
**Pull request by Shade-**
This is a basic integration for StackExchange network using HybridAuth, as requested in #590. Change "stackoverflow" with other sites in their network to login with them. This is needed because their OAuth implementation requires a specific site.

Feel free to merge & add extra features.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Thank you!

**Comment by VladyslavKurmaz** [comment]
@Shade- I found two issues with StackExchange provider (from my perspective)

* Provider's class should be placed in
/hybridauth/additional-providers/hybridauth-stackexchange\Providers\StackExchange.php
instead of
/hybridauth/additional-providers
like any other additional providers

* Provider's class file name should have php extension *StackExchange.php*, file *StackExchange* has no extension now

**Comment by Shade-** [comment]
Yeah sorry, they should have been fixed by now (see comments above).

**Comment by christ0ph3r** [comment]
I sumbitted PR for and last commit is for this https://github.com/hybridauth/hybridauth/pull/598

**Pull request merged**
