### PR TITLE
Move Vkontakte fields to configuration

### PR DESCRIPTION
**Pull request by TrogWarZ**
1. Now you can use HybridAuth config to set fields that will be taken from [VKontakte](https://vk.com/) for [users.get](https://vk.com/dev/users.get) and [friends.get](https://vk.com/dev/friends.get)
2. Refactor code to use api_base_url from \OAuth2Client

### CODE REVIEW

**Comment by nazar-pc** [comment]
This doesn't seem to be backward compatible.
Maybe, better assume old fields by default, but allow to redefine it using configuration?

**Comment by TrogWarZ** [comment]
@nazar-pc, can you provide example when it breaks something? I'll fix this shortly.

But i think they are backward-compatible. PR just add some new fields, but not removes old (see code below).
All fields, that defined in \Hybrid_User_Contact but not got from Vkontakte, wil be null but they will exist.

```php
public $fiends = [
    'identifier'  => 'uid',            // Old field saved
    'firstName'   => 'first_name',     // Old field saved
    'lastName'    => 'last_name',      // Old field saved
    'gender'      => 'sex',            // Old field saved
    'displayName' => 'screen_name',    // Old field saved
    'city'        => 'city',           // New one
    'country'     => 'country',        // New one
    'bdate'       => 'bdate',          // Old field saved
    'photoURL'    => 'photo_max_orig', // Old field saved
    'nickname'    => 'nickname',       // Old field saved
    'domain'      => 'domain',         // New one
    'timezone'    => 'timezone',       // Old field saved
    'photo_rec'   => 'photo_rec',      // Old field saved
    'photo_max'   => 'photo_max',      // New one
    'home_phone'  => 'home_phone',     // New one
    'home_town'   => 'home_town',      // Old field saved
];
```

**Comment by TrogWarZ** [comment]
Okay, i've change field map to make compability more clearly. Check this out, please.

**Comment by nazar-pc** [comment]
Ah, sorry, looks like I understood it wrong, seems to be fine indeed, did you test it (because I didn't yet)?

**Comment by TrogWarZ** [comment]
Yep, i use this code in my project and tested compability version from master and from my PR. It's good, just added new fields.

**Pull request merged**
