### PR TITLE
Remove Google Plus support in v2

### LINKED ISSUE #1024: Login with google+ going deprecated ?
https://github.com/zorn-v/nextcloud-social-login/issues/69

### PR DESCRIPTION
**Pull request by karlshea**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Fixes #1024 for v2
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | Not sure
| Minor: New Feature?      | Sort of
| Documentation PR         | 

Backport changes from 6123c31 for v2. I think I removed the right things, and login is working for me, but we don't use the Contacts API so I'm not sure if everything is right there.

### CODE REVIEW

**Comment by bien119** [comment]
Anyone has any update for hybridauth v2.12.0?

**Comment by karlshea** [comment]
> Anyone has any update for hybridauth v2.12.0?

That's what this is.

**Comment by ApacheEx** [comment]
Thank you for your help. I will check this PR today

**Comment by ApacheEx** [comment]
Great job, thanks 🥇

**Comment by jinjie** [comment]
@karlshea @ApacheEx

Awesome guys! Is there a documentation on such migration? Such as generating new keys on the console.

I think there was some discussion where a new v2 api key is required to make this work? Correct me if I'm wrong.

**Comment by ApacheEx** [comment]
you are welcome 😃 

I'm preparing release notes for v2.13, will describe there what to do and how.

**Comment by driade** [comment]
@ApacheEx Please note the link to this issue on https://github.com/hybridauth/hybridauth/releases is wrong.

**Pull request merged**
