### PR TITLE
Hybridauth 3

### PR DESCRIPTION
**Pull request by miled**
I'm making this PR to whom may want to comment on the topic.

After two long breaks, the way overdue Hybridauth 3 remake has reached beta stage, and I'm hoping to merge it to master branch once I sort out the library documentation. Understandably, the current codebase of Hybridauth 2.9 will live on a separate branch and will be kept in maintenance mode.

* Source: https://github.com/hybridauth/hybridauth/tree/3.0.0-Remake 
* Progression: https://github.com/hybridauth/hybridauth/blob/3.0.0-Remake/TODO.md 
* Online documentation: https://hybridauth.github.io/ 

To test it locally using composer:

```
php composer.phar require hybridauth/hybridauth dev-3.0.0-Remake
```

Implemented providers features so far:

Provider            | Specs   | Authentication | User Profile | User Contacts | User Status  | User Activities 
------------------- | ------- | -------------- | ------------ | ------------- | ------------ | --------------- 
Facebook            | OAuth2  | [X]            | [X]          | [X]           | [X]          | [X]
Twitter             | OAuth1  | [X]            | [X]          | [X]           | [X]          | [X]
Google              | OAuth2  | [X]            | [X]          | [X]           |              |
GitHub              | OAuth2  | [X]            | [X]          |               |              |
Reddit              | OAuth2  | [X]            | [X]          |               |              |
BitBucket           | OAuth2  | [X]            | [X]          |               |              |
WordPress           | OAuth2  | [X]            | [X]          |               |              |
Tumblr              | OAuth1  | [X]            | [X]          |               | [X]          |
Disqus              | OAuth2  | [X]            | [X]          |               |              |
Dribbble            | OAuth2  | [X]            | [X]          |               |              |
Windows Live        | OAuth2  | [X]            | [X]          | [X]           |              |
Foursquare          | OAuth2  | [X]            | [X]          | [X]           |              |
Instagram           | OAuth2  | [X]            | [X]          |               |              |
LinkedIn            | OAuth2  | [X]            | [X]          |               |              |
Yahoo               | OAuth2  | [X]            | [X]          |               |              |
Vkontakte           | OAuth2  | [X]            | [X]          |               |              |
Mailru              | OAuth2  | [X]            | [X]          |               |              |
StackExchange       | OAuth2  | [X]            | [X]          |               |              |
OpenID              | OpenID  | [X]            | [X]          |               |              |
PaypalOpenID        | OpenID  | [X]            | [X]          |               |              |
StackExchangeOpenID | OpenID  | [X]            | [X]          |               |              |
YahooOpenID         | OpenID  | [X]            | [X]          |               |              |
AOLOpenID           | OpenID  | [X]            | [X]          |               |              |
Steam               | Hybrid  | [X]            | [X]          |               |              |
Discord             | OAuth2  | [X]            | [X]          |               |              |
TwitchTV            | OAuth2  | [X]            | [X]          |               |              |

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Amazing! Glad to have you back!

**Comment by miled** [comment]
Thanks @StorytellerCZ,

I did manage to finish a good chunk of the documentation. Are there tasks that remains to be done on current master branch before we may proceed to merge it with 3.0.0-Remake?

**Comment by collizo4sky** [comment]
So good to have you back @miled 

I was actually sad when it place in maintenance mode.

**Comment by StorytellerCZ** [comment]
@miled Current tasks... Well there is the ongoing issue with Facebook and other outdated providers, but I think we will just push everyone to v3.
We should probably release a beta version or release candidate for v3 so that we can get more testing from others and it will get some attention from plugin developers and so on.

**Comment by miled** [comment]
Thanks @collizo4sky.

@StorytellerCZ, alright. I'll merge v3 within the upcoming days.

**Pull request merged**
