### PR TITLE
Clean up. Add new example. Coding Standards fixes

### PR DESCRIPTION
**Pull request by ApacheEx**

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
I think we might want to consider moving examples into their own repository.

**Comment by ApacheEx** [comment]
@StorytellerCZ, yeah it would be nice when user can check the code and try how it works at the same time.

**Comment by ApacheEx** [comment]
btw, any chance to make me as collaborator here as well ?
https://github.com/hybridauth/hybridauth.github.io

we can think later how to organize examples for hybridauth.

**Comment by StorytellerCZ** [comment]
I'm afraid not, not even I have access to that. We need @miled to finish the transition to full FOSS in that regard.

**Comment by ApacheEx** [comment]
Do you know how to contact with him? 😅

**Comment by StorytellerCZ** [comment]
@ApacheEx It's been a while since I saw @miled around.

**Comment by PrplHaz4** [comment]
@ApacheEx @StorytellerCZ, @miled used to respond to the support address...might be worth a shot? hybridauth@gmail.com

**Pull request merged**
