### PR TITLE
Add BitBucket Provider

### PR DESCRIPTION
**Pull request by gabrielsomoza**

### CODE REVIEW

**Comment by gabrielsomoza** [comment]
This is not completely ready yet, still need to actually run it and make sure it works.

**Comment by gabrielsomoza** [comment]
Alright, tested it and it works! Let me know if you need anything else in order to merge this.

**Comment by AdwinTrave** [comment]
Thank you! The only other thing is that you can make a documentation page with all the necessities on the `gh-pages` branch.

**Comment by gabrielsomoza** [comment]
Ok - when is this scheduled to be released? Just to make sure I add the docs before that.

**Comment by AdwinTrave** [comment]
When I get time to resolve some other issues like #406 and #408. Some of it depends on @miled, but I think I'll get the time 2 weeks from now to do all the work for release, but no longer then 3 weeks.

**Pull request merged**
