### PR TITLE
Fix fatal error during Facebook provider initialization (both for composer and non composer installation)

### PR DESCRIPTION
**Pull request by ApacheEx**
PR with fix for #698. Works well in both cases (composer and non-composer installation of Facebook SDK)

### CODE REVIEW

**Comment by Kirancloudnix** [comment]
SHould we upgrade the facebook graph SDK, ALso please update with clear instructions

**Comment by ApacheEx** [comment]
@Kirancloudnix,

if you check composer.json - there is dependency: "facebook/graph-sdk": "^5.4". So it's already the latest version.

about PR:
1. If you clone hybridauth repository and then run "composer install":
    - you will see "vendor" directory in the root of the library which has facebook/graph-sdk and autoload.php (generated by composer)
    - so, this PR checks if there is "/vendor/autload.php" file and if so require it.
    - if somehow "vendor" directory was moved to another one, then you can provide a custom path in config.php (path_vendor) 
2. If you have hybridauth library without composer installation:
    - Facebook SDK should be placed in /hybridauth/Hybrid/thirdparty/Facebook
    - so, this PR checks if there is "/hybridauth/Hybrid/thirdparty/Facebook/autload.php" file and if so require it.

that's it. Hopefully it's quite understandable.

**Comment by Kirancloudnix** [comment]
Thanks @ApacheEx

**Comment by StorytellerCZ** [comment]
@ApacheEx Could you also add info about this into documentation? Thanks!

**Comment by TheJoin95** [comment]
NOTE: if you run composer install in an other directory, you will have a different level for the vendor's path

**Comment by dereuromark** [comment]
This actually seems to break things, see my comment @ https://github.com/hybridauth/hybridauth/issues/773 :/

Downgrading to 2.9.1 removed the fatal error for the time being.

**Comment by TheJoin95** [comment]
@dereuromark Yeah, it's because you have vendor directory in some other level of directory.
You can fix this by edit the vendor variable's path with your.

**Comment by dereuromark** [comment]
No, it is all default - see https://github.com/ADmad/CakePHP-HybridAuth/blob/master/composer.json
Breaking existing applications in a bugfix release is not acceptable IMO.

**Comment by happyman** [comment]
⁣發送自 BlueMail ​

2017年4月16日 上午9:26, 上午9:26，在 Miki <notifications@github.com> 已写:

**Comment by ApacheEx** [comment]
@dareoromark,
it seems you should change path_vendor in your hybridauth/config.php. Make sure it leads to your vendor/autoload.php, then it should work.
p.s it's not broken release, it's just wrong configuration.

**Comment by sunaryohadi** [comment]
I am using custom array for config along with other component setting in my Application.

So, if I change Auth.php line 76,

`$config["path_vendor"] = realpath(dirname(__FILE__) . "/../../vendor");`
to
`$config["path_vendor"] = realpath(dirname(__FILE__) . "/../../../../../vendor");`

It run correctly.

**Comment by ApacheEx** [comment]
@sunaryohadi, @dereuromark I have created a PR with fixes for autoload.php. Now, it should work for all cases. Please check it out #776

**Comment by sunaryohadi** [comment]
The PR is working very well in my case .... Good job.

**Pull request merged**
