### PR TITLE
LinkedIn API v2 support.

### PR DESCRIPTION
**Pull request by janadam-hbf**
Add LinkedIn API 2 support. Change r_basicprofile to r_liteprofile.

### CODE REVIEW

**Comment by ApacheEx** [comment]
I'm wondering why all lines are modified? could you change only needed ? it's quite hard to review

**Comment by janadam-hbf** [comment]
I also fixed line endings to LF in this PR.
To see actual changes, you can check "Hide whitespace changes" under "Diff settings" on "Files Changed" tab. Please see screenshot attached.
Screenshot from 2019-03-26 06-29-14

**Comment by hsuk-404** [comment]
Is this commit tested? 

I merged this commit with hybrid-2.9.6 and I am getting this following error:
Original error message: Authentication failed! LinkedIn returned an error: unauthorized_scope_error

**Comment by ApacheEx** [comment]
closed in favor of #1076

**Pull request closed without merging**
