### PR TITLE
Added actual coding standards

### PR DESCRIPTION
**Pull request by lsolesen**
I've added the actual coding standards based on PSR2 that this library is coded after. If accepted we could fix some of the coding standard issues quite easily with `phpcbf`

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
I'm all for this, but will have to defer to @miled for the final OK.

**Comment by nazar-pc** [comment]
I'd say all stuff of this kind should only target 3.x branch. And 3.x should be fixed as alpha release and finally moving towards stable. Otherwise 2.x diverges further and it would be very difficult to bring everything back.

**Comment by lsolesen** [comment]
I think the commit can safely be added. It does not break anything and test
will pass as the phpcs.xml reflects the current coding standards. That will
help not introduce other violations. Then in 3.x branch we can remove the
modifications to the psr2 coding standard and get 3.x closer to psr2. If
you accept and merge the pull request into 3.x branch also.I will help fix
up the violations.

Den man. 2. maj 2016 02.42 skrev Nazar Mokrynskyi <notifications@github.com

**Comment by StorytellerCZ** [comment]
I plan to release 2.7 some time this month. If we don't hear from @miled soon I will merge this. @lsolesen Feel free to go ahead and create PR for the 3.0 branch with stricter rules.

**Comment by StorytellerCZ** [comment]
Will include this in v2.9

**Pull request merged**
