### PR TITLE
Fix Travis CI build (fix phpcs and remove php 5.3)

### PR DESCRIPTION
**Pull request by ApacheEx**
## Goal

Now, every Travis CI build to branch v2 failed, because of wrong coding standards in some files and not supported php 5.3 by facebook/graph-sdk.

## Description

1. This PR fixes Coding Standards by running:
`phpcbf --standard=phpcs.xml additional-providers hybridauth`

2. This PR fixes an error with `facebook/graph-sdk requires PHP 5.4`
It's from travis-ci logs:
```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - facebook/graph-sdk 5.5.0 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - facebook/graph-sdk 5.4.4 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - facebook/graph-sdk 5.4.3 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - facebook/graph-sdk 5.4.2 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - facebook/graph-sdk 5.4.1 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - facebook/graph-sdk 5.4.0 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
    - Installation request for facebook/graph-sdk ^5.4 -> satisfiable by facebook/graph-sdk[5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.4.4, 5.5.0].
```

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Great work! We might need to make it explicit in the documentation that Facebook provider requires php 5.4 even though the rest  of HA is fine with 5.3. Which is why I would like if we can figure out how to still retain php 5.3 testing, but given that majority of people are already at higher versions I don't think this really matters that much. Thoughts?

**Comment by ApacheEx** [comment]
@StorytellerCZ,
currently, we have only phpcs testing in Travis CI. 
As solution, we can skip `composer install` for php 5.3, what do you think?

**Comment by StorytellerCZ** [comment]
@ApacheEx Thanks! I think that sounds good for now.

**Comment by StorytellerCZ** [comment]
I'm merging for now to have a better reporting on other PRs.

**Pull request merged**
