### PR TITLE
Proposal: make $supportRequestState property public so it can be chan…

### PR DESCRIPTION
**Pull request by w3guy**
…ge after Provider instantiation.

| Q                        | A
| ------------------------ | ---
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes

We are using a session storage that doesn't persist on page reload and as a result would prefer to disable support for state in some adapter.

Making this public would allow us to stop creating new classes all in a bid to disable the property.

### CODE REVIEW

**Comment by w3guy** [comment]
What do you think @ApacheEx ?

**Comment by ApacheEx** [comment]
> What do you think @ApacheEx ?

Hi, probably we can add a public method instead, smth like: setSupportState

**Comment by w3guy** [comment]
> > What do you think @ApacheEx ?
> 
> Hi, probably we can add a public method instead, smth like: setSupportRequestState

That would be better. Should I modify the PR to reflect that?

**Comment by ApacheEx** [comment]
Yes, please 👌

**Comment by ApacheEx** [comment]
also, we can achieve this by using config inside configure method.

something like:

```php
if ($this->config->exists('supportRequestState')) {
    $this->supportRequestState = $this->config->get('supportRequestState');
}

**Comment by w3guy** [comment]
> also, we can achieve this by using config inside configure method (preferable).
> 
> something like:
> 
> ```
> if ($this->config->exists('supportRequestState')) {
>     $this->supportRequestState = $this->config->get('supportRequestState');
> }
> ```

Done. Please review

**Review by ApacheEx — APPROVED** [review]
Looks good, will be released in 3.9 soon

**Pull request merged**
