### PR TITLE
[Odnoklassniki] Refactoring and add $fields variable

### PR DESCRIPTION
**Pull request by enjoyiacm**
* Add ``$fields`` variable;
* Change ``pic_1`` to ``pic190x190``;
* Change ``pic_2`` to ``pic640x480``;
* Refactoring.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Currently unmergable, please fix.

**Comment by enjoyiacm** [comment]
How? I don't understand..

**Comment by StorytellerCZ** [comment]
@enjoyiacm Please merge the newest changes into your branch. That should show you what you need to fix or fix the problem the automatic system is having.

**Comment by nazar-pc** [comment]
There is `rebase` git command for this, just rebase your branch against master branch of this repository

**Comment by enjoyiacm** [comment]
How to make this from GitHub site? I don't have git console.

**Comment by fortis** [comment]
Hi enjoyiacm, I can help, add me in skype: imacoda

**Comment by enjoyiacm** [comment]
Okay, forget .. There has been automerge status of all successful checks, but for some reason no one has done merge. I will use my local version.

Let go to [my fork](https://github.com/enjoyiacm/hybridauth/blob/f2282c9c29de40d5f4f1cb0ef7e8967aa8c2deee/additional-providers/hybridauth-odnoklassniki/Providers/Odnoklassniki.php) and to the code itself is copied.

**Comment by nazar-pc** [comment]
Well, sometimes you have to wait for merge. Nothing special here, I wonder why you're not just rebasing it, such things happen sometimes.

**Comment by nazar-pc** [comment]
Moreover, you'll need to merge changes from upstream anyway if you want to have working version in future.

**Comment by enjoyiacm** [comment]
@nazar-pc one more time: «There has been automerge status of all successful checks...», but you merge another — #578 — to master branch and my changes — not actually now. But my changes wait 7 days to merge (with OK all status), and #578 only 6 days! 7 > 6 — you know, but #578 merge first!

**Comment by enjoyiacm** [comment]
And one more thing.

My changes is ``Improvement``, and #578 changes is not important, 'cause provider Odnoklassniki still work fine without this changes (try from [this site](http://goodcookin.ru), if you're not trust).

**Comment by nazar-pc** [comment]
@enjoyiacm, one more time: such things happen sometimes. You have to be patient, sometimes other changes are easier to review/more important and after merging those you have to rebase your changes. This is completely OK, you don't have to write multiple messages about it, just rebase and wait.

For instance, you can see my non-merged PRs to Google's Polymer library: https://github.com/Polymer/polymer/pulls/nazar-pc
The oldest is from 5th of August. I did multiple rebases and updates to keep all of them up to date. And I'm slowly pushing developers, but they also have other stuff to do, they have own regular work, families, friends and bunch of other things.

You're not the center of the universe, everyone here is also spending their own time and no one pay them for it. Respect this and patient, please. No one here (especially maintainers) HAVE TO merge this, but they DO IT regularly on a voluntary basis, it just takes time.

**Comment by enjoyiacm** [comment]
@nazar-pc my ``baby rage`` is only for this things:

> «There has been automerge status of all successful checks...», but you merge another — #578 — to master branch and my changes — not actually now. But my changes wait 7 days to merge (with OK all status), and #578 only 6 days! 7 > 6 — you know, but #578 merge first! 

And this:

> My changes is Improvement, and #578 changes is not important, 'cause provider Odnoklassniki still work fine without changes in #578 (try from this site, if you're not trust).

**Pull request merged**
