### PR TITLE
Apply some PSR-2 standards rules

### PR DESCRIPTION
**Pull request by Soullivaneuh**
This PR applies most of the PSR-2 (and 1) standards.

This was made with the great [PHP Coding Standards Fixer](http://cs.sensiolabs.org/) tool.

I put the list of applied fixers. You can see what was did here: http://cs.sensiolabs.org/#usage

Applied fixers:

 * indentation
 * parenthesis
 * trailing_spaces
 * braces
 * eof_ending
 * function_call_space
 * function_declaration
 * lowercase_constants
 * lowercase_keywords
 * method_argument_space
 * visibility

Symfony [code standards](http://symfony.com/doc/current/contributing/code/standards.html) could be also applied. This is not required but I recommend to use it. Tell me if you want it so I will update this PR (or make another one).

I also updated `.editorconfig` file and added `fabpot/php-cs-fixer` as dev dependencies to make contributor using it.

Two another things could be done after this:

 * Subscribe to [Scrutinizer CI](https://scrutinizer-ci.com/) to get informed of code quality variations. See an example here: https://github.com/Soullivaneuh/IsoCodesValidator (badges)
 * Update `CONTRIBUTING.md` file to talk about the new style guide.

This PR is a **proposition** related to #34 and #459. I'm waiting your opinions and questions.

You can obviously not accept it but I think it would be a great improvement to get PSR-2 compliant onto this project, before 3.0 stable.

Best regards

### CODE REVIEW

**Comment by miled** [comment]
I wish to keep the current style. The reason why I didn't use PSR-2 is because it's a recommendation more than a standard, besides it does not bring any additional value.

V3 will be PSR-1 and PSR-4 compliant, tho.

**Comment by nazar-pc** [comment]
Same for me to be honest. Even more, PSR is just recommendation from group of people that develop frameworks, even inside this group some people voted against, so this is not "standard", just recommendation, compromise of some set of representatives.

But I think it is a good idea to have some specified code style (do we have any?). Might be good to include code style config for popular IDEs into repository, so that anyone can use it out of the box.

Which code style to choose is not as important as to be consistent across project.

P.S. Scrutinizer is awesome, we should definitely start using it) I'm using it in my project and quite happy with it.

**Comment by Soullivaneuh** [comment]
@miled 

> PSR-2 is because it's a recommendation more than a standard

I'm curious of why your are saying that. Can you please explain it?

I suggested PSR-2 because it's the must use standard/recommendation on recent projects. This is why it could be great to have it a the new fresh version of HybridAuth.

Refered from the [PSR-2 introduction](http://www.php-fig.org/psr/psr-2/#coding-style-guide) extract:

> The intent of this guide is to reduce cognitive friction when scanning code from different authors.

> Thus, the benefit of this guide is not in the rules themselves, but in the sharing of those rules.

To answer of this:

> besides it does not bring any additional value.

I don't agree (surprise! ;-) ). Beside the advantage of following a common standard, you have many advantages on the code itself, take a look to the doc.

For example, the indenting note: http://www.php-fig.org/psr/psr-2/#2.4.-indenting

Or another sample: Avoid using both upper-cased and down-cased keywords (`true`, `false`, `null`, `array`...) in order to keep code coherence.

@nazar-pc 

> Might be good to include code style config for popular IDEs into repository, so that anyone can use it out of the box.

> Which code style to choose is not as important as to be consistent across project.

PSR-2 is the most followed by popular IDE like PHPStorm. It's a new argument to use it. :+1: 

Note: About indenting, for example, your `.editorconfig` force 8 column space per tab, this produce a hardly readable code.

> Scrutinizer is awesome, we should definitely start using it) I'm using it in my project and quite happy with it.

Yes, but by default Scrutinizer wouldn't like you if you don't follow PSR-2, isn't it? (just a question) :-)


---

After all, thanks guy to participate to this discussion. :+1:

**Comment by PrplHaz4** [comment]
@miled @nazar-pc  that is largely true for an individual developer, but the fact is this is now a community project getting contributions from all over.

PSR-2 is a simple, well understood guideline that is easy to apply and pretty thoroughly documented.  I don't necessarily agree with all of the guidelines but IMO, having a standard that is easy to follow is more important than wasting time on a holy war over spaces and tabs.

**Comment by Soullivaneuh** [comment]
> that is largely true for an individual developer, but the fact is this is now a community project getting contributions from all over.

Exactly what I was trying to say. :+1: 

> I don't necessarily agree with all of the guidelines but IMO.

Yes. This is why I applied only some of the fixers for the moment. Let's Scrutinizer say what could be improved (or not) after.

**Comment by Soullivaneuh** [comment]
Maybe should we call HybridAuth contributors/users to vote about this suggestion to get an global idea of the opinion?

**Comment by miled** [comment]
> Maybe should we call HybridAuth contributors/users to vote about this suggestion to get an global idea of the opinion?

I don't think that would be necessary. People will most definitely vote for a familiar standard over personal preferences. so, let settle for PSR-2..

> P.S. Scrutinizer is awesome, we should definitely start using it) I'm using it in my project and quite happy with it.

I'm already using both scrutinizer and codeclimate on my fork, but tbh I prefer codeclimate cause scrutinizer tends to complaint, a lot.

https://scrutinizer-ci.com/g/miled/hybridauth/
https://codeclimate.com/github/miled/hybridauth/

**Comment by nazar-pc** [comment]
> PSR-2 is the most followed by popular IDE like PHPStorm. It's a new argument to use it. :+1:

True, but I have own code style for my projects as well as public repository with code style configuration.

> Note: About indenting, for example, your .editorconfig force 8 column space per tab, this produce a hardly readable code.

Agree, 8 is too much 4 is more common and readable for PHP

> Yes, but by default Scrutinizer wouldn't like you if you don't follow PSR-2, isn't it? (just a question) :-)

To be honest I don't know. I mean is has extremely limited configuration for code style at the moment, so it does give me some unrelated patches suggestions. I've reported such an issue for them, we'll see how they will deal with that. But I'm currently reformatting code in IDE according to configured code style automatically, so, it is not a big issue for me.

@Soullivaneuh, I agree do not mix tabs and spaces, do not mix uppercase and lowercase keywords and so on. That is just what I say - consistency.

Anyway, when I'm joining any side project I'm accepting their codestyle, independently of what it is.

**Comment by nazar-pc** [comment]
Also, Scrutinizer will punish more because of code duplication, wrong or incomplete PhpDoc sections and overcomplicated code parts, code style is, mostly, a matter of taste.

**Comment by Soullivaneuh** [comment]
I heard and understood your arguments, you know mines. :+1: 

Let's waiting some contributors reactions on this PR, must be interesting.

**Comment by nazar-pc** [comment]
I'd not expect too much reactions, although 209 people should read this message, as usual, most of them are not active.
There is @AdwinTrave who have also write access to this repository, and someone else, don't remember exactly whom. Would be good to hear what they think is they care about this topic.

**Comment by danizord** [comment]
:+1:

**Comment by AdwinTrave** [comment]
I'm all for using the PSR standards. It makes it easy to reference and many developers are already familiar with them. In the end any style guide is better then nothing.
@SocalNick

**Comment by Soullivaneuh** [comment]
Please don't hesitate to ping me for branch rebase if change was made on the project.

**Comment by Soullivaneuh** [comment]
Thanks. :+1: 

I will take a look on CONTRIBUTING later and make a PR about that.

**Pull request merged**
