### PR TITLE
Update Yandex.php

### LINKED ISSUE #1279: Invalid photoURL in the Yandex provider
## Bug

'http://upics.yandex.net/' . $userProfile->identifier . '/normal' gives 404 error

### PR DESCRIPTION
**Pull request by pgroot91**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Fixes #1279 
| Patch: Bug Fix?          | Bug Fix
| Major: Breaking Change?  | No
| Minor: New Feature?      | No

Made some small changes fixing the avatarURL and First and Last Name.

### CODE REVIEW

**Comment by ApacheEx** [comment]
Hello, will have a look on it when CI will be green. So, pls fix reported errors first.

**Comment by pgroot91** [comment]
Also fixed @ApacheEx

**Review by ApacheEx — APPROVED** [review]

**Comment by ApacheEx** [comment]
Once more, thank you 🥇

**Comment by ApacheEx** [comment]
it was removed intentionally due to russian invasion of Ukraine. All their providers are removed and not supported anymore. If you want to use it somehow, you still could fork it and add by self which sounds for me more like you support them

**Pull request merged**
