### PR TITLE
Required api version number in requests Vkontakte provider

### PR DESCRIPTION
**Pull request by andreypaa**
## Summary

* Addition

## Goal

Correct api request to VK.com

## Description

Required api version number in requests

### CODE REVIEW

**Comment by ApacheEx** [comment]
Makes sense, thanks.

**Comment by dimabory** [comment]
@ApacheEx will be fixed in 2.x?

**Comment by ApacheEx** [comment]
@dimabory, welcome to create a PR for v2  😃 . 
I can create a PR as well (but it will be next week)

**Comment by docxplusgmoon** [comment]
How I can can get these changes from composer?

**Comment by ApacheEx** [comment]
@docxplusgmoon,
It will be released soonly with other fixes. Currently, you can use `3.0.x-dev` tag.

**Pull request merged**
