### PR TITLE
Add new provider

### PR DESCRIPTION
**Pull request by endgame99**
Add new provider GloboFace
100264021-eb853280-2f56-11eb-8f07-04cff3fa8d75

### CODE REVIEW

**Comment by ApacheEx** [comment]
what you want to achieve? why you create a PR from v4 branch to master?

**Comment by endgame99** [comment]
where should request new provider?

**Comment by endgame99** [comment]
elsewhere it cannot be opened.

**Comment by ApacheEx** [comment]
for sure not in Pull Requests which are needed for making changes in the code.

here is a link to fill a new issue: https://github.com/hybridauth/hybridauth/issues/new

**Comment by endgame99** [comment]
I wanted you to add a new provider. 
I want to make a login system with globoface.com

**Comment by ApacheEx** [comment]
this is the wrong place to discuss. Please rise a new issue. And maybe somebody will help you.

**Pull request closed without merging**
