### PR TITLE
Add support for multipart requests for video upload support

### PR DESCRIPTION
**Pull request by pb30**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | No
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes
| Documentation PR         | No

Update Http interfaces to support multipart requests to support file uploads through apiRequest

```
$facebookAdapter->apiRequest('https://graph-video.facebook.com/xyz/videos',
                                  'POST',
                                  [
                                          'title'       => $videoTitle,
                                          'description' => $videoDescription,
                                          'source'      => new \CURLFile($videoPath),
                                  ],
                                  [],
                                  true
        );
```

### CODE REVIEW

**Comment by merkuriy** [comment]
👍

**Comment by StorytellerCZ** [comment]
Could you please create a PR for the `gh-pages` branch and add documentation about this feature? Thanks!

**Comment by pb30** [comment]
@StorytellerCZ It looks like `gh-pages` is docs for v2.x? Is there a branch/repo for 3.x?

**Comment by ApacheEx** [comment]
@pb30 for v3 there is separate repo: https://github.com/hybridauth/hybridauth.github.io

**Comment by pb30** [comment]
https://github.com/hybridauth/hybridauth.github.io/pull/10

**Comment by ApacheEx** [comment]
Thanks a lot 🥇

p.s sorry for waiting.

**Pull request merged**
