### PR TITLE
Use authorization header instead of query parameter for call to accou…

### PR DESCRIPTION
**Pull request by guillaumev**
…nt.json

Removed the access_token from the GET parameters and put it in the Authorization header instead.

### CODE REVIEW

**Comment by guillaumev** [comment]
@ApacheEx Could this be merged in HybridAuth v2 ? Thank you.

**Comment by ApacheEx** [comment]
Yeah, it looks good. 
Sorry for waiting 👍

**Comment by guillaumev** [comment]
Thank you :+1:

**Comment by chamsocha** [comment]
Hello guillaume, do you have humanitarianId provider for non joomla website, custom php website

**Pull request merged**
