### PR TITLE
Return back support for PHP 5.2

### PR DESCRIPTION
**Pull request by misterspelik**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Yes, returned back support for PHP 5.2
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Documentation PR         | Replaced [] to array()

Changes in 4 files in Providers/ folder to make the code support PHP 5.2 again. Replaced [] construction to array() declaration.

### CODE REVIEW

**Comment by misterspelik** [comment]
@ApacheEx You have a lot of places where described about PHP 5.2, at least composer.json.
All another places in the code are using array() construction.

I know about that these versions are dead but please write below and try to understand the use case please.

This branch contains the old code itself and so-so mantained. But what`s the real reason of declining this PR.
Especially when there are a lot of servers working with the old code (as our particular application) without possibility to migrate to new version of PHP due to old framework (which means to rewrite all application).

Another question is that v2 branch will not work at new PHP anyway and this is totally not needed because of 3.0 version development.

What would you suggest to do in this case?

P. S. 
Yes for sure I can use the forked repo but the goal is to use original one because of some critical fixes which might appear from community or finding something by myself and deliver to another users.

**Comment by StorytellerCZ** [comment]
@ApacheEx as much as I agree with the sentiment, @misterspelik isn't wrong either.

@ApacheEx I think we should probably merge this and release a patch version for the 2.x branch since 3.x is still in RC and release 3.x branch ASAP so that we can close support for 2.x for good and put even more pressure on people to migrate. Let's set a date for this.

@misterspelik seriously though update your app. If this is a production app, it should not run on that old PHP.

**Comment by ApacheEx** [comment]
Ok, guys. Thanks for explanation. 

p.s. To release v3 we need to fix/improve documentation which is the hardest part 😥 Would be nice if somebody can help.

**Comment by misterspelik** [comment]
@ApacheEx I think I can participate to this process somehow. I will contact you directly about that

**Pull request merged**
