### PR TITLE
Adds file storage

### PR DESCRIPTION
**Pull request by WinterSilence**
Stored data in temp file

| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | no
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | yes

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Can you explain a bit about this?

**Comment by WinterSilence** [comment]
@StorytellerCZ temp file better than session: no output problems (cookie session),  lifetime is longer.

**Comment by REJack** [comment]
There is no identifier per user like session does it in background, I guess this allows to use the saved data from the temp file even if you use a other browser/computer.
For security reasons we should use one temp file per user to seperate the prodvider infos but this would need an user identifier to set/get the right infos.

**Comment by WinterSilence** [comment]
@REJack [adds `md5(get_current_user())` to filename](https://github.com/hybridauth/hybridauth/blob/bd2eefdfa753d03d23ce68c5215cbc361bcb3af7/src/Storage/TempFile.php#L36). Cookie's session have similar problem.

**Comment by StorytellerCZ** [comment]
@WinterSilence Could you please also prepare a PR for the docs?

**Comment by REJack** [comment]
@WinterSilence get_current_user() is not for stuff like this, it‘s gets the name of the owner of the current PHP script, it would result even to one file only. 

Cookie session doesn't have problems like this, the data’s are stored on the user's computer so only the user that logged in to a provider would have a cookie with the data and the user could only fetch his data and not from any other user.

**Comment by WinterSilence** [comment]
@REJack 

pls, show example for this problem

> user could only fetch his data and not from any other use

not in all OS

**Comment by REJack** [comment]
@WinterSilence I've created a demo, you can test it [here](https://hybridauth-test.rejack.space/) I logged into Facebook and you can use the "Session" on every other browser/computer.

**Pull request closed without merging**
