### PR TITLE
setApiEndpoints() must be an instance of Hybridauth\Data\Collection

### PR DESCRIPTION
**Pull request by dusta**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Update docs
| Patch: Bug Fix?          | -
| Major: Breaking Change?  | -
| Minor: New Feature?      |
| Documentation PR         | 

``` php
Fatal error: Uncaught TypeError: Argument 1 passed to Hybridauth\Adapter\AbstractAdapter::setApiEndpoints() must be an instance of Hybridauth\Data\Collection, array given

```

### CODE REVIEW

**Comment by ApacheEx** [comment]
You are 100% right. Good catch 👍 


I think `Data\Collection` is something internal, so it's better to change a bit `setApiEndpoints` to accept array of endpoints and then wrap it to the `new Data\Collection($endpoints)`

what do you think?

**Comment by dusta** [comment]
Yes, it will be more convenient. I already updated branch.

**Comment by ApacheEx** [comment]
Thank you, it looks great 💯

**Comment by ApacheEx** [comment]
@zorn-v I've added backward compatibility, thank you for noticing.

**Comment by zorn-v** [comment]
Thanks. In future it might be deprecated, but across RCs...
BTW. When release ? 😄

**Comment by ApacheEx** [comment]
@zorn-v you are right, it's ready ☺️. 

2 tasks are left: https://github.com/hybridauth/hybridauth/milestone/2
I really hope that during February, HA 3.0 will be released.

**Pull request merged**
