### PR TITLE
New QQ Provider.

### PR DESCRIPTION
**Pull request by holmescn**
The QQ provider is reimplemented. The original one add many custom function that helps get the user id and user profile. I have rewritten the provider based on github provider. No additional function are needed, all request sent and retrieved by OAuth2Client class.

I have no idea about whether I should add a new provider instead of override the original one.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
I'm mostly hesitant as this breaks existing functionality.

Could you re-implement the old functions and add depreciated log message? Then in 2.8 or 2.9 we can remove the old functionality.

**Comment by holmescn** [comment]
The original implementation just do redundant works that HybridAuth already done. I don't think anything should be marked as depreciated because they are different implementation. If I do it, perhaps everything in the original one will be marked deprecated, and should be eliminated in the next version.

**Comment by christ0ph3r** [comment]
Found 1 spelling error 

deocde

**Comment by christ0ph3r** [comment]
We should always try out best not to break things for others.

**Comment by holmescn** [comment]
I thought the best way is to make another PR that rename my implementation.

**Pull request closed without merging**
