### PR TITLE
Add ORCID provider

### LINKED ISSUE #1006: [provider] ORCID
Add support for [ORCID](https://orcid.org/) provider. It uses RESTful API and OAuth 2.0.

Documentation for APIs: https://members.orcid.org/api/
Difference between APIs: https://orcid.org/about/membership/comparison/

Public API introduction: https://support.orcid.org/hc/en-us/articles/360006897174/
Public API documentation: https://members.orcid.org/api/about-public-api/

### PR DESCRIPTION
**Pull request by filips123**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Fixes #1006
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes
| Documentation PR         | No

I created ORCID provider for auth and user profile. Because results from it's API are in XML, I also added XML parser to `Data\Parser`. Documentation of supported providers is also updated.

### CODE REVIEW

**Comment by filips123** [comment]
@StorytellerCZ @ApacheEx Can you merge this?

**Comment by StorytellerCZ** [comment]
Can you please prepare documentation PR for this? Thanks!

**Comment by filips123** [comment]
@StorytellerCZ Documentation is in hybridauth/hybridauth.github.io#8.

**Comment by filips123** [comment]
@ApacheEx @StorytellerCZ Ping.

**Comment by ApacheEx** [comment]
Thanks a lot. Looks good for me and sorry for waiting so long.

**Pull request merged**
