### PR TITLE
Make Hybrid_Endpoint methods non-static

### PR DESCRIPTION
**Pull request by nazar-pc**
Changed static methods to dynamic, also constructor added.
`::process` method left for backward-compatibility and calls constructor.

Should not break any existing code using this according to documentation.
Also big question whether we need all that methods and properties to be public?

### CODE REVIEW

**Comment by AdwinTrave** [comment]
I agree with you, but would appreciate @miled feedback on this before merge.

**Comment by miled** [comment]
this class is definitely better now. thank you!

> Also big question whether we need all that methods and properties to be public?
no. only `::process` need to be public, everything else can be protected.

**Comment by nazar-pc** [comment]
Just made everything except `::process()` and constructor protected

**Comment by AdwinTrave** [comment]
Got an error:
```
Severity: Parsing Error
Message: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$'
Filename: Hybrid/Endpoint.php
Line Number: 69
```

specifically here:
```php
public static function process( $request = NULL )
{
	new static( $request );
}
```

**Comment by nazar-pc** [comment]
Is that PHP 5.2?

**Comment by nazar-pc** [comment]
Can't remember when I touched 5.2 last time, anyway, should work now as late static binding for modern versions, and as just `self` for 5.2

**Comment by AdwinTrave** [comment]
Darm, looks like it. I fixed my hosting to 5.4, but the fix worked as well, at least we won't hear complains from legacy people.

**Pull request merged**
