### PR TITLE
Update GitHub provider to recognize verified email

### LINKED ISSUE #702: GitHub provider does not indicate verified email address.
The GitHub OAuth API indicates whether an email address has been verified, but this GitHub provider for HybridAuth isn't yet checking for or using that information. I'll submit a PR for that in a moment.

### PR DESCRIPTION
**Pull request by forevermatt**
I tried to follow the existing coding style. Fixes #702.

### CODE REVIEW

**Comment by forevermatt** [comment]
The GitHub OAuth documentation about users is at https://developer.github.com/v3/users/emails/

**Comment by forevermatt** [comment]
If you would like me to go ahead and update the changelog as part of this PR, should I use 2.8.1 as the next version (since this is essentially a bug fix)? I would have submitted this PR against develop, but there didn't seem to be a develop branch.

**Comment by StorytellerCZ** [comment]
Yes, v2.8.1. Thanks a lot!

**Comment by forevermatt** [comment]
@StorytellerCZ Okay, done. Thanks! 😃

**Pull request merged**
