### PR TITLE
Avoid isset checks.

### PR DESCRIPTION
**Pull request by ADmad**
Improves code readability.

### CODE REVIEW

**Comment by nazar-pc** [comment]
+1

**Comment by miled** [comment]
@ADmad it's conflicting with @nazar-pc's pr. would you submit a new one please.

**Comment by ADmad** [comment]
@miled I have rebased the patch. It's not mergeable. Should have just merged my patch instead of his :)

**Comment by nazar-pc** [comment]
I'll make more changes to that file soon, can include this fix

**Comment by ADmad** [comment]
Rebased one more and last time :stuck_out_tongue:

**Comment by miled** [comment]
thank you :d

**Pull request merged**
